import { defaultSoundPreferences } from "./soundDefaults";
import { iconSvgFor } from "./quickActionIcons";
import type {
  AppSettings,
  BootstrapState,
  InputRuntimeSnapshot,
  LocalSharedDirectory,
  NotificationView,
  RemoteFileEntry,
  RemoteFileShare,
} from "./types";

type BridgeMockData = {
  state: BootstrapState;
  appSettings: AppSettings;
  notifications: NotificationView[];
  inputRuntime: InputRuntimeSnapshot;
  remoteShares: RemoteFileShare[];
  localShares: LocalSharedDirectory[];
  remoteDirectories: Map<string, RemoteFileEntry[]>;
};

export const mockData: BridgeMockData = {
  state: {
    revision: 0,
  port: 8765,
  serverRunning: true,
  actions: [
    {
      id: "action-dev",
      name: "启动开发环境",
      icon_id: "terminal",
      icon_svg: iconSvgFor("terminal"),
      color: "#252A34",
      group: "开发",
      sort_order: 0,
      source_preset_id: null,
      revision: 0,
      confirm_before_run: false,
      action_type: {
        type: "ShellCommand",
        command: "cd ~/projects/my-app\nnpm install\nnpm run dev",
        working_dir: "~/projects/my-app",
      },
      actionTypeLabel: "Shell 脚本",
      isToggle: false,
      isRunning: false,
      requiresConfirmation: false,
      globalShortcutError: null,
    },
    {
      id: "action-folder",
      name: "打开工作目录",
      icon_id: "folder",
      icon_svg: iconSvgFor("folder"),
      color: "#3B82F6",
      group: "开发",
      sort_order: 1,
      source_preset_id: null,
      revision: 0,
      confirm_before_run: false,
      action_type: { type: "LaunchApp", app_name: "Finder", app_path: null },
      actionTypeLabel: "打开文件夹",
      isToggle: false,
      isRunning: false,
      requiresConfirmation: false,
      globalShortcutError: null,
    },
    {
      id: "action-music",
      name: "播放专注歌单",
      icon_id: "play",
      icon_svg: iconSvgFor("play"),
      color: "#9333EA",
      group: "媒体",
      sort_order: 2,
      source_preset_id: null,
      revision: 0,
      confirm_before_run: false,
      action_type: {
        type: "AppleScript",
        script: 'tell application "Music" to play playlist "Focus"',
      },
      actionTypeLabel: "媒体播放",
      isToggle: false,
      isRunning: false,
      requiresConfirmation: false,
      globalShortcutError: null,
    },
    {
      id: "action-git",
      name: "Git 推送",
      icon_id: "terminal",
      icon_svg: iconSvgFor("terminal"),
      color: "#F15A3C",
      group: "开发",
      sort_order: 3,
      source_preset_id: null,
      revision: 0,
      confirm_before_run: false,
      action_type: {
        type: "ShellCommand",
        command: "git push",
        working_dir: "~/projects/my-app",
      },
      actionTypeLabel: "Shell 脚本",
      isToggle: false,
      isRunning: false,
      requiresConfirmation: false,
      globalShortcutError: null,
    },
    {
      id: "action-db",
      name: "本地数据库启动",
      icon_id: "toggle",
      icon_svg: iconSvgFor("toggle"),
      color: "#22A06B",
      group: "开发",
      sort_order: 4,
      source_preset_id: null,
      revision: 0,
      confirm_before_run: false,
      action_type: {
        type: "ToggleShellCommand",
        start_command: "docker compose up -d db",
        stop_command: "docker compose stop db",
        working_dir: "~/projects/my-app",
      },
      actionTypeLabel: "开关命令",
      isToggle: true,
      isRunning: false,
      requiresConfirmation: false,
      globalShortcutError: null,
    },
    {
      id: "action-capture",
      name: "截取并复制",
      icon_id: "crosshair",
      icon_svg: iconSvgFor("crosshair"),
      color: "#111827",
      group: "常用",
      sort_order: 5,
      source_preset_id: null,
      revision: 0,
      confirm_before_run: false,
      action_type: {
        type: "Hotkey",
        modifiers: ["command", "shift"],
        key: "4",
      },
      actionTypeLabel: "自动化",
      isToggle: false,
      isRunning: false,
      requiresConfirmation: false,
      globalShortcutError: null,
    },
  ],
  connectedDevices: [{ id: "device-iphone", name: "我的 iPhone", autoConnect: true }],
  pairedDevices: [
    { id: "device-iphone", name: "我的 iPhone", autoConnect: true },
    { id: "device-ipad", name: "iPad Pro", autoConnect: false },
  ],
  pendingPairing: null,
  outgoingPairings: [],
  inputPermission: "Granted",
  activeInputDevice: null,
  inputMetrics: null,
  activity: ["我的 iPhone 已连接", "服务已启动，端口 8765"],
  unreadNotificationCount: 2,
  mcpRunning: true,
  mcpPort: 8766,
  privacy: {
    active: false,
    manualEnabled: false,
    mirrorDetected: false,
    activationSource: "off",
    visibleProtectedWindows: [],
    settings: {
      autoEnableOnMirror: true,
      allowRemoteActions: true,
      maskStyle: "frosted",
      protectedApps: [
        { name: "微信", identifier: "com.tencent.xinWeChat", path: null, enabled: true },
        { name: "钉钉", identifier: "com.alibaba.DingTalkMac", path: null, enabled: true },
        { name: "飞书", identifier: "com.bytedance.Feishu", path: null, enabled: true },
      ],
    },
  },
  },
  appSettings: {
    revision: 0,
  deviceName: "",
  theme: "light",
  language: "system",
  launchAtStartup: false,
  launchSilently: false,
  autoUpdateEnabled: true,
  updateChannel: "stable",
  sounds: defaultSoundPreferences(),
  notifications: {
    enabled: true,
    onlyWhenInactive: true,
    showPreviews: false,
    pairingRequests: true,
    transferRequests: true,
    transferCompleted: true,
    transferFailed: true,
    remoteFileCompleted: true,
    remoteFileFailed: true,
    printCompleted: false,
    printFailed: true,
    deviceConnections: false,
    workflowActionRequired: true,
    workflowCompleted: false,
    workflowFailed: true,
    inputPermissionRequired: true,
    agentNotifications: true,
    updateAvailable: true,
  },
  clipboardEnabled: true,
  clipboardShortcut: "CmdOrCtrl+Shift+V",
  clipboardAutoFocusSearch: true,
  clipboardSortBy: "updatedAt",
  clipboardSyncEnabled: true,
  clipboardSyncUpdateSystemClipboard: true,
  clipboardSyncEditsAndDeletes: true,
  clipboardSyncFavorites: true,
  nearbyDiscoverable: true,
  enhancedScreenshotEnabled: false,
  screenshotShortcut: "CmdOrCtrl+Shift+A",
  screenshotIncludeCursor: false,
  screenshotFormat: "png",
  screenshotFileNameTemplate: "Screenshot_{date}_{time}",
  webFiles: { enabled: true, port: 8767, bindMode: "lanOnly", siteName: "", sessionIdleMinutes: 720, allowVpnPrivate: false },
  },
  notifications: [
  {
    id: "notification-action-required",
    title: "需要确认：继续实现 MCP 通知",
    body: "请确认是否继续基于当前方案实现 MCP 通知功能。Host 将自动完成离线保管、多设备投递与已读聚合。",
    source: "Codex · ArcRelay",
    kind: "action_required",
    reference: "ArcRelay",
    createdAtMs: Date.now() - 8 * 60 * 1000,
    readAtMs: null,
    readByDeviceName: null,
    deliveryState: "unread",
  },
  {
    id: "notification-completed",
    title: "任务完成：通知方案已整理",
    body: "通知方案和 Host 端确认机制已经整理完成。",
    source: "Codex · ArcRelay",
    kind: "task_completed",
    reference: "ArcRelay",
    createdAtMs: Date.now() - 44 * 60 * 1000,
    readAtMs: Date.now() - 40 * 60 * 1000,
    readByDeviceName: "我的 iPhone",
    deliveryState: "read",
  },
  {
    id: "notification-waiting",
    title: "设备离线，等待上线后送达",
    body: "手机上线并连接 Host 后将拉取这条通知。",
    source: "Codex · ArcRelay",
    kind: "info",
    reference: null,
    createdAtMs: Date.now() - 24 * 60 * 60 * 1000,
    readAtMs: null,
    readByDeviceName: null,
    deliveryState: "waitingForDevice",
  },
  ],
  inputRuntime: {
    revision: 0,
  productId: "com.arcrelay.input",
  serviceInstanceId: "browser-preview",
  localOperatingSystem: "MacOs",
  remoteOperatingSystems: { "remote-office-mac": "MacOs" },
  capabilities: {
    canCapturePointer: true,
    canCaptureKeyboard: true,
    canSuppressLocalInput: true,
    canPlaceInternalBarrier: false,
    canInjectAbsolutePointer: true,
    canInjectKeyboard: true,
    canInjectAppPointer: false,
    canControlElevatedApps: false,
    canPersistPermission: true,
    canCaptureNativeQuartzEvents: true,
    canInjectNativeQuartzEvents: true,
    canCapturePrecisionTouchpadEvents: false,
    canInjectPrecisionTouchpadEvents: false,
    canCaptureSystemGestures: false,
    systemGestureFormatVersion: 0,
    consumerCaptureMask: 255,
    consumerInjectMask: 255,
    brightnessDisplayIds: [],
    canInjectSystemGestures: false,
    limitation: null,
  },
  configuration: {
    version: 2,
    inputSharingEnabled: true,
    topologyAuthor: "browser-preview",
    layout: {
      workspaceId: "browser-workspace",
      revision: 1,
      displays: {
        "browser-display": {
          displayId: "browser-display",
          deviceId: "browser-preview",
          fingerprint: "browser-preview-display",
          name: "Studio Display 27″",
          pixelSize: { width: 2560, height: 1440 },
          logicalBounds: { x: 0, y: 0, width: 1280, height: 720 },
          scaleFactor: 2,
          physicalSizeUm: { width: 597000, height: 336000 },
          rotation: "Degrees0",
          deskRectUm: { x: 0, y: 0, width: 597000, height: 336000 },
          geometryConfidence: "HardwareReported",
          inventoryRevision: 1,
        },
        "browser-laptop": {
          displayId: "browser-laptop",
          deviceId: "browser-preview",
          fingerprint: "browser-preview-laptop-display",
          name: "MacBook Pro 14″",
          pixelSize: { width: 3024, height: 1964 },
          logicalBounds: { x: 1280, y: 120, width: 1512, height: 982 },
          scaleFactor: 2,
          physicalSizeUm: { width: 302000, height: 196000 },
          rotation: "Degrees0",
          deskRectUm: { x: 0, y: 336000, width: 302000, height: 196000 },
          geometryConfidence: "HardwareReported",
          inventoryRevision: 1,
        },
        "remote-display": {
          displayId: "remote-display",
          deviceId: "remote-office-mac",
          fingerprint: "remote-office-display",
          name: "Dell U2723QE 27″",
          pixelSize: { width: 2560, height: 1440 },
          logicalBounds: { x: 0, y: 0, width: 2560, height: 1440 },
          scaleFactor: 1,
          physicalSizeUm: { width: 597000, height: 336000 },
          rotation: "Degrees0",
          deskRectUm: { x: 597000, y: 50000, width: 597000, height: 336000 },
          geometryConfidence: "UserCalibrated",
          inventoryRevision: 3,
        },
      },
      portals: [
        {
          portalId: "auto-preview-studio-to-dell",
          sourceDisplay: "browser-display",
          sourceEdge: "Right",
          sourceSegment: { startUm: 50000, endUm: 336000 },
          targetDisplay: "remote-display",
          targetEdge: "Left",
          targetSegment: { startUm: 0, endUm: 286000 },
          direction: "Bidirectional",
          activationPolicy: "Immediate",
          allowWhileDragging: true,
          insetUm: 500,
          hysteresisUm: 500,
          status: "Active",
        },
        {
          portalId: "auto-preview-studio-to-laptop",
          sourceDisplay: "browser-display",
          sourceEdge: "Bottom",
          sourceSegment: { startUm: 0, endUm: 302000 },
          targetDisplay: "browser-laptop",
          targetEdge: "Top",
          targetSegment: { startUm: 0, endUm: 302000 },
          direction: "Bidirectional",
          activationPolicy: "Immediate",
          allowWhileDragging: false,
          insetUm: 500,
          hysteresisUm: 500,
          status: "Active",
        },
      ],
    },
    rememberedDisplays: {},
    excludedDisplays: [],
    keyboardProfiles: [
      { name: "日常办公", kind: "Productivity", revision: 1, textStrategy: "UseTargetLayout", semanticOverrides: [] },
      { name: "终端", kind: "Terminal", revision: 1, textStrategy: "UseTargetLayout", semanticOverrides: [] },
      { name: "开发工具", kind: "Ide", revision: 1, textStrategy: "UseTargetLayout", semanticOverrides: [] },
      { name: "远程桌面", kind: "RemoteDesktop", revision: 1, textStrategy: "FollowSourceText", semanticOverrides: [] },
      { name: "游戏 · 原始按键", kind: "GameRaw", revision: 1, textStrategy: "FollowSourceText", semanticOverrides: [] },
      { name: "演示", kind: "Presentation", revision: 1, textStrategy: "UseTargetLayout", semanticOverrides: [] },
    ],
    activeKeyboardProfile: "Productivity",
    rightOptionRawMode: true,
    horizontalScrollBehavior: "NativeScroll",
    consumerShortcuts: [],
  },
  discoveredPeers: ["remote-office-mac", "nearby-guest-mac"],
  nearbyPeers: [
    {
      serviceInstanceId: "remote-office-mac",
      displayName: "书房 Mac mini",
      addresses: ["10.1.1.54"],
      port: 52197,
      certificateSha256: "AF2238115BC0189A118E42DBB317AA6079DC11820CF0724E2F95D18C0B11A920",
      capabilityDigest: "desktop-input-full",
      paired: true,
      connected: true,
      capabilities: {
        canCapturePointer: true,
        canCaptureKeyboard: true,
        canSuppressLocalInput: true,
        canPlaceInternalBarrier: false,
        canInjectAbsolutePointer: true,
        canInjectKeyboard: true,
        canInjectAppPointer: false,
        canControlElevatedApps: true,
        canPersistPermission: true,
        canCaptureNativeQuartzEvents: true,
        canInjectNativeQuartzEvents: true,
        canCapturePrecisionTouchpadEvents: false,
        canInjectPrecisionTouchpadEvents: false,
        canCaptureSystemGestures: false,
        systemGestureFormatVersion: 0,
        consumerCaptureMask: 255,
        consumerInjectMask: 255,
        brightnessDisplayIds: [],
        canInjectSystemGestures: false,
        limitation: null,
      },
    },
    {
      serviceInstanceId: "nearby-guest-mac",
      displayName: null,
      addresses: ["10.1.1.249"],
      port: 51515,
      certificateSha256: "91C25AA2B41FD3C7C6AF0C54E0A30737ED1E1F93026CB7B8B1836271C0AA60B2",
      capabilityDigest: "desktop-input-full",
      paired: false,
      connected: false,
      capabilities: null,
    },
  ],
  connectedPeers: ["remote-office-mac"],
  displayAvailability: { "browser-display": "Ready", "browser-laptop": "Ready", "remote-display": "Ready" },
  controller: null,
  controlEpoch: null,
  captureActive: true,
  diagnostics: Array.from({ length: 24 }, (_, index) => ({
    timestampMs: Date.now() - (23 - index) * 30_000,
    category: "input-e2e",
    message: index === 20 ? "书房 Mac mini 自动重连" : index === 22 ? "控制会话开始" : index === 23 ? "穿越到 Dell U2723QE" : "输入链路采样正常",
    latencyMicros: [6200, 7100, 5800, 6600, 7400, 8200, 6900, 6100][index % 8],
  })),
  },
  remoteShares: [
  { id: "team-space", name: "团队空间", writable: true },
  { id: "project-archive", name: "项目归档", writable: false },
  { id: "public-assets", name: "公共素材", writable: true },
  ],
  localShares: [
  { id: "local-design", name: "设计交付", path: "/Users/demo/Design/交付", writable: true, web: { mode: "password", listed: true, allowPreview: true, allowDownload: true, slug: "design-demo-share", hasPassword: true, credentialRevision: 1 } },
  { id: "local-public", name: "公共素材", path: "/Users/demo/Shared/公共素材", writable: false, web: { mode: "public", listed: true, allowPreview: true, allowDownload: true, slug: "public-demo-share", hasPassword: false, credentialRevision: 0 } },
  ],
  remoteDirectories: new Map<string, RemoteFileEntry[]>([
  ["team-space:", [
    { name: "设计资料", relativePath: "设计资料", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2026, 7, 29, 2, 42) },
    { name: "开发文档", relativePath: "开发文档", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2026, 7, 28, 9, 18) },
    { name: "市场资料", relativePath: "市场资料", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2026, 7, 27, 6, 8) },
    { name: "会议记录", relativePath: "会议记录", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2026, 7, 26, 12, 31) },
  ]],
  ["team-space:设计资料", [
    { name: "品牌资源", relativePath: "设计资料/品牌资源", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2026, 7, 29, 2, 42) },
    { name: "产品截图", relativePath: "设计资料/产品截图", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2026, 7, 29, 1, 31) },
    { name: "交付文档", relativePath: "设计资料/交付文档", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2026, 7, 28, 8, 18) },
    { name: "设计规范", relativePath: "设计资料/设计规范", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2026, 7, 27, 3, 7) },
    { name: "原型文件", relativePath: "设计资料/原型文件", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2026, 7, 25, 6, 22) },
    { name: "ArcRelay_演示稿.pptx", relativePath: "设计资料/ArcRelay_演示稿.pptx", kind: "file", size: 19_503_514, modifiedAtMs: Date.UTC(2026, 7, 29, 3, 23) },
    { name: "产品路线图.xlsx", relativePath: "设计资料/产品路线图.xlsx", kind: "file", size: 220_160, modifiedAtMs: Date.UTC(2026, 7, 29, 2, 58) },
    { name: "接口说明.pdf", relativePath: "设计资料/接口说明.pdf", kind: "file", size: 1_258_291, modifiedAtMs: Date.UTC(2026, 7, 28, 7, 40) },
    { name: "启动页预览.png", relativePath: "设计资料/启动页预览.png", kind: "file", size: 2_831_155, modifiedAtMs: Date.UTC(2026, 7, 28, 6, 11) },
    { name: "组件库.fig", relativePath: "设计资料/组件库.fig", kind: "file", size: 10_276_045, modifiedAtMs: Date.UTC(2026, 7, 27, 9, 33) },
    { name: "需求文档.docx", relativePath: "设计资料/需求文档.docx", kind: "file", size: 446_464, modifiedAtMs: Date.UTC(2026, 7, 27, 2, 12) },
    { name: "设计素材包.zip", relativePath: "设计资料/设计素材包.zip", kind: "file", size: 134_217_728, modifiedAtMs: Date.UTC(2026, 7, 26, 13, 5) },
    { name: "更新记录.txt", relativePath: "设计资料/更新记录.txt", kind: "file", size: 2_048, modifiedAtMs: Date.UTC(2026, 7, 26, 10, 44) },
    { name: "操作演示.mp4", relativePath: "设计资料/操作演示.mp4", kind: "file", size: 47_500_083, modifiedAtMs: Date.UTC(2026, 7, 25, 8, 30) },
    { name: "界面设计.psd", relativePath: "设计资料/界面设计.psd", kind: "file", size: 80_530_636, modifiedAtMs: Date.UTC(2026, 7, 24, 5, 55) },
    { name: "图标集.sketch", relativePath: "设计资料/图标集.sketch", kind: "file", size: 27_682_406, modifiedAtMs: Date.UTC(2026, 7, 24, 3, 9) },
    { name: "用户反馈.csv", relativePath: "设计资料/用户反馈.csv", kind: "file", size: 38_912, modifiedAtMs: Date.UTC(2026, 7, 23, 12, 21) },
  ]],
  ["project-archive:", [
    { name: "2025", relativePath: "2025", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2026, 0, 5, 4, 0) },
    { name: "2024", relativePath: "2024", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2025, 0, 3, 4, 0) },
  ]],
  ["public-assets:", [
    { name: "品牌模板", relativePath: "品牌模板", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2026, 7, 21, 4, 0) },
    { name: "通用图标", relativePath: "通用图标", kind: "folder", size: 0, modifiedAtMs: Date.UTC(2026, 7, 18, 4, 0) },
  ]],
  ]),
};
